#!/bin/bash
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 200, "green": 0, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 200, "green": 0, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 200, "green": 0, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 200, "green": 0, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 200, "green": 0, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 10, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 10, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 10, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 10, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 10, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 90}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 90}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 90}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 90}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 90}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 180}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 180}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 180}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 180}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 180}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 270}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 270}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 270}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 270}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROTATE", "Config": {"heading": 270}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "ROLL", "Config": {"speed": 30, "durationInSecs": 1}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player1/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 0, "green": 200, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player2/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 0, "green": 200, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player3/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 0, "green": 200, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player4/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 0, "green": 200, "blue": 0}}'
mosquitto_pub -h sphero.local -p 1883 -t spheroRallye/player5/adHocAction -m '{"ActionType": "SET_RGB", "Config": {"red": 0, "green": 200, "blue": 0}}'